<?php
namespace Admin\Controller;
// 产品列表Tab标签管理
class ProjectGroupTagController extends AdminController {

    private  $projectGroupTagObj ;

    public function  _initialize(){
        $this->projectGroupTagObj = M('project_group_tag');
        return parent::_initialize(); // TODO: Change the autogenerated stub

    }

    public function index(){
        $list = $this->projectGroupTagObj->where('is_delete =1')->select();
        $this->assign('list',$list);
        $this->display();
    }

    public function add(){
        if(!IS_POST){
            $page = I('get.p', 1, 'int');

            $params = array(
                'page' => $page,
            );
            $this->assign('params', $params);
            $this->display();
        }else {
            $page = I('post.page', 1, 'int');
            $dataTime = date('Y-m-d H:i:s', time());
            $tag = I('post.tag', '', 'strip_tags');
            $row = array(
                'tag' => $tag,
                'add_time' => $dataTime,
                'modify_time' => $dataTime,
                'add_user_id' => $this->uid,
            );
            $rid = $this->projectGroupTagObj->add($row);
            if (!$rid) $this->ajaxReturn(array('status' => 0, 'info' => '添加失败,请重试'));
            $this->ajaxReturn(array('status' => 1, 'info' => C('ADMIN_ROOT') . '/projectGroupTag/index/p/' . $page));
        }
    }

    public function edit(){
        if(!IS_POST){
            $id = I('get.id', 0, 'int');
            $page = I('get.p', 1, 'int');

            $params = array(
                'page' => $page,
            );
            $this->assign('params', $params);

            $detail = $this->projectGroupTagObj->where(array('is_delete'=>1,'id'=>$id))->find();
            if(!$detail){
                $this->error('Tab标签不存在或已被删除');exit;
            }
            $this->assign('detail', $detail);
            $this->display();
        }else {
            $page = I('post.page', 1, 'int');
            $id = I('post.id', 0, 'int');
            if (!$id) {
                $this->ajaxReturn(array('status' => 0, 'info' => '标签不存在！'));
            }
            $tag = I('post.tag', '', 'strip_tags');
            $isShow = I('post.is_show', 1, 'int');

            $data = array();

            if ($tag) {
                $data['tag'] = $tag;
            }
            if ($isShow) {
                $data['is_show'] = $isShow;
            }
            $data['modify_user_id'] = $this->uid;
            $data['modify_time'] = date('Y-m-d H:i:s', time());



            if (!$this->projectGroupTagObj->where('id = ' . $id)->save($data)) $this->ajaxReturn(array('status' => 0, 'info' => '编辑失败,请重试'));
            $this->ajaxReturn(array('status' => 1, 'info' => C('ADMIN_ROOT') . '/projectGroupTag/index/p/' . $page));
        }
    }

    public function delete(){
        $id = I('post.id', 0, 'int');

        $info = $this->projectGroupTagObj->field('id,is_show')->where(array('id' => $id, 'is_delete' => 1))->find();

        if (!$info) $this->ajaxReturn(array('status' => 0, 'info' => 'Tab标签不存在或已被删除'));

        $data = array(
            'is_delete'=>0
        );
        if (!$this->projectGroupTagObj->where('id = ' . $id)->save($data)) $this->ajaxReturn(array('status' => 0, 'info' => '删除失败,请重试'));
        $this->ajaxReturn(array('status' => 1, 'info' => C('ADMIN_ROOT') . '/projectGroupTag/index/'));
    }

    public function show(){
       // $id = I('get.id', 0, 'int');
        $isShow = I('post.is_show',0, 'int');

        $data = array(
            'is_show'=>$isShow,
        );
        if (!$this->projectGroupTagObj->where('is_delete = 1')->save($data)) $this->ajaxReturn(array('status' => 0, 'info' => '更新失败,请重试'));

        $this->ajaxReturn(array('status' => 1, 'info' => '') );
    }
}